### ISSUE TITLE
在眼镜RG-202上，运行sdk_facesdk_demo-11ce62b，有一次相机预览没有

### ISSUE THREAD

**Issue by qxq2020** [RokidGlass/glass2-docs#156]
在眼镜RG-202上，运行sdk_facesdk_demo-11ce62b，第一次人脸相机自动识别黑屏，没视频预览。

https://user-images.githubusercontent.com/20652538/126726888-5d184aa4-69a8-415a-acd1-98174d9a27ab.mp4

https://user-images.githubusercontent.com/20652538/126726917-0b0c7816-25fc-412f-b9cb-9179fad8c71b.mp4

日志是这样的：
`2021-07-22 19:47:49.710 8044-8044/com.rokid.rokidfacesample W/ActivityThread: handleWindowVisibility: no activity for token android.os.BinderProxy@cd2565a
2021-07-22 19:47:49.797 8044-8258/com.rokid.rokidfacesample W/CameraBase: An error occurred while connecting to camera 0: Status(-8): '7: connectHelper:1333: Higher-priority client using camera, ID "0" currently unavailable'
2021-07-22 19:47:49.797 8044-8258/com.rokid.rokidfacesample W/System.err: java.lang.RuntimeException: Fail to connect to camera service
2021-07-22 19:47:49.798 8044-8258/com.rokid.rokidfacesample W/System.err:     at android.hardware.Camera.<init>(Camera.java:546)
2021-07-22 19:47:49.798 8044-8258/com.rokid.rokidfacesample W/System.err:     at android.hardware.Camera.open(Camera.java:392)
2021-07-22 19:47:49.798 8044-8258/com.rokid.rokidfacesample W/System.err:     at com.rokid.camerakit.cameralibrary.CameraManage.openCamera(CameraManage.java:52)
2021-07-22 19:47:49.798 8044-8258/com.rokid.rokidfacesample W/System.err:     at com.rokid.camerakit.cameralibrary.view.CameraView$3.run(CameraView.java:98)
2021-07-22 19:47:49.799 8044-8258/com.rokid.rokidfacesample W/System.err:     at android.os.Handler.handleCallback(Handler.java:873)
2021-07-22 19:47:49.799 8044-8258/com.rokid.rokidfacesample W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:99)
2021-07-22 19:47:49.799 8044-8258/com.rokid.rokidfacesample W/System.err:     at android.os.Looper.loop(Looper.java:193)
2021-07-22 19:47:49.799 8044-8258/com.rokid.rokidfacesample W/System.err:     at android.os.HandlerThread.run(HandlerThread.java:65)
2021-07-22 19:47:49.870 8044-8044/com.rokid.rokidfacesample E/[cit_faceeng_video]: dumpiqa false
2021-07-22 19:47:49.870 8044-8044/com.rokid.rokidfacesample E/[cit_faceeng_video]: dumpfeat false
2021-07-22 19:47:49.872 8044-8044/com.rokid.rokidfacesample E/[TownLine] [searchengine] [JNI]: dumprecog true
2021-07-22 19:47:49.893 8044-8258/com.rokid.rokidfacesample W/CameraBase: An error occurred while connecting to camera 0: Status(-8):`

**Comment by lanyuqingri** [comment]
看粘贴的日志来看是第一次进入时相机打开错误，导致没有预览：  An error occurred while connecting to camera 0: Status(-8): '7: connectHelper:1333: Higher-priority client using camera, ID "0" currently unavailable

**Comment by qxq2020** [comment]
你好，现在我们的需求是识别到人脸，需要上传到后台，后台进行人脸对比。
目前的问题：
1.videoFace.startTrack 回调的 faceDO.recogBitmap 为null,拿不到人脸照片数据
2.人脸识别的时候，会回调很多重复人脸的信息，我们需要拿到去重复的人脸图片上传给后台，后台来进行处理。
请问我怎么拿到人脸识别的图片和去重复，选一个高质量的人脸图片上传到我们的服务器。
帮忙给出处理方法，和相关代码的处理。谢谢

**Comment by qxq2020** [comment]
麻烦解决一下

**Comment by lanyuqingri** [comment]
1. faceDO.recogBitmap 是本地识别到具体人之后会有赋值，如果需要检测到人脸后上传后台，需要拿到人脸质量分之后，根据质量分来判断满不满足上传质量要求，满足则通过faceDO的人脸框位置从videoFace.getByte()中抠出对应人脸【请注意线程调度，如需要异步处理，先把获取的大图数据拷贝出来再去抠图】
2. 人脸识别回调的FaceDO中会有一个trackId的字段，这个字段表示的是人脸跟踪ID，对同一个人来说，只要没出预览区域并且特征没丢失，trackId是不变的，可以通过trackId进行过滤，针对同一个trackId，在一段时间周期内拿到质量分最高的人脸抠图送到服务器上

**Comment by qxq2020** [comment]
你好
1.关于上述功能 是否有参考代码参考一下。
2.我们使用CameraX的api实现的相机预览界面，我们怎样在我们的CameraX api相机界面使用人脸识别的功能？有没相应代码参考一下

**Comment by lanyuqingri** [comment]
1. 人脸抠图相关的可以通过以下形式： 
            Rect faceRect = faceDO.toRect(CameraParams.PREVIEW_WIDTH,CameraParams.PREVIEW_HEIGHT);    //拿到faceDO中人脸框在预览区域的坐标位置
            Rect finalRect = FaceRectUtils.scaleRect(faceRect,CameraParams.PREVIEW_WIDTH,CameraParams.PREVIEW_HEIGHT,1.6f);   //以人脸框区域中心为原点，人脸框区域放大1.6倍
            Bitmap bm = BitmapUtils.nv21ToBitmap(rawData,CameraParams.PREVIEW_WIDTH,CameraParams.PREVIEW_HEIGHT,finalRect);    //通过从大图中抠出人脸

BitmapUtils.nv21ToBitmap的实现如下
public static Bitmap nv21ToBitmap(byte[] nv21, int width, int height, Rect rect) {
        Bitmap bitmap = null;
        try {
            YuvImage image = new YuvImage(nv21, ImageFormat.NV21, width, height, null);
            ByteArrayOutputStream stream = new ByteArrayOutputStream();
            if (rect.left < 0) {
                rect.left = 0;
            }
            if (rect.right > width) {
                rect.right = width;
            }
            if (rect.top < 0) {
                rect.top = 0;
            }
            if (rect.bottom > height) {
                rect.bottom = height;
            }

            image.compressToJpeg(rect, 100, stream);
            bitmap = BitmapFactory.decodeByteArray(stream.toByteArray(), 0, stream.size());
            stream.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
        return bitmap;
    }


2. 人脸识别相关的功能不依赖具体的camera api，从sdk的设计上看，只是需要业务方往里边送入camera预览数据，格式是NV21，只要咱们这边用CameraX的api拿到camera预览数据，然后通过sdk接口送入sdk即可。具体如何送入sdk可以参考demo中送入的方式

**Comment by qxq2020** [comment]
> 1. 人脸抠图相关的可以通过以下形式：
>    Rect faceRect = faceDO.toRect(CameraParams.PREVIEW_WIDTH,CameraParams.PREVIEW_HEIGHT);    //拿到faceDO中人脸框在预览区域的坐标位置
>    Rect finalRect = FaceRectUtils.scaleRect(faceRect,CameraParams.PREVIEW_WIDTH,CameraParams.PREVIEW_HEIGHT,1.6f);   //以人脸框区域中心为原点，人脸框区域放大1.6倍
>    Bitmap bm = BitmapUtils.nv21ToBitmap(rawData,CameraParams.PREVIEW_WIDTH,CameraParams.PREVIEW_HEIGHT,finalRect);    //通过从大图中抠出人脸
> 
> BitmapUtils.nv21ToBitmap的实现如下
> public static Bitmap nv21ToBitmap(byte[] nv21, int width, int height, Rect rect) {
> Bitmap bitmap = null;
> try {
> YuvImage image = new YuvImage(nv21, ImageFormat.NV21, width, height, null);
> ByteArrayOutputStream stream = new ByteArrayOutputStream();
> if (rect.left < 0) {
> rect.left = 0;
> }
> if (rect.right > width) {
> rect.right = width;
> }
> if (rect.top < 0) {
> rect.top = 0;
> }
> if (rect.bottom > height) {
> rect.bottom = height;
> }
> image.compressToJpeg(rect, 100, stream);
> bitmap = BitmapFactory.decodeByteArray(stream.toByteArray(), 0, stream.size());
> stream.close();
> } catch (Exception e) {
> e.printStackTrace();
> }
> return bitmap;
> }
> 
> 1. 人脸识别相关的功能不依赖具体的camera api，从sdk的设计上看，只是需要业务方往里边送入camera预览数据，格式是NV21，只要咱们这边用CameraX的api拿到camera预览数据，然后通过sdk接口送入sdk即可。具体如何送入sdk可以参考demo中送入的方式

1.faceDO.recogBitmap 是本地识别到具体人之后会有赋值，是指我们本地上传人脸照片到数据库，然后人脸识别到了，才会给faceDO.recogBitmap赋值是吧。否则本地数据库没传人脸照片，识别到的faceDO.recogBitmap都是为null，需要按照上面提供的方法去取照片是吧。
2.是否是像demo中， videoFace.setData(new VideoInput(bytes));传入NV21格式的流就可以使用人脸识别的功能是吧？
     * 处理相机返回数据
     */
    private void initCam() {
        cameraView.addPreviewCallBack((bytes, camera) -> {
            //将相机数据放入SDK
            if (videoFace != null&&!stop) {
                videoFace.setData(new VideoInput(bytes));
            }
        });
    }

**Comment by lanyuqingri** [comment]
嗯嗯，1/2两个问题您的理解是正确的

**Comment by qxq2020** [comment]
现在我们项目的需求是，希望在眼镜的任何界面都能一直进行着人脸识别（相当于一个后台任务），识别到人脸后上传后台。请问这种功能能做吗？

**Comment by lanyuqingri** [comment]
可以的，只要获取camera数据的线程再应用进程内一直运行，然后不停的向算法喂数据，算法会一直回调数据上来，然后应用可以根据需要做自己的业务逻辑

**Comment by qxq2020** [comment]
你好，还有一个问题，我们需要拿到设备的sn号。1.我通过Build.SERIAL去取sn号，为unkown。2.在RKGlassDevice#initUsbDevice(...)回调函数中，我们可以获取到眼镜的基本信息GlassInfo，sn 区分眼镜唯一标识序列号。
是不是眼镜的ID，不管连盒子还是Android设备都是通过2来获得的。

**Comment by lanyuqingri** [comment]
通过盒子（二代Dock）获取设备序列号的方法是获取ro.serialno 属性的值，眼镜和盒子有 不同的SN，同时眼镜接盒子和接手机Android设备SN获取的方式不一样。如果接盒子的话，建议获取ro.serialno 属性值拿到设备SN，这个也跟我们这边设备记录跟踪一致的

**Comment by shiwf** [comment]
> 你好，还有一个问题，我们需要拿到设备的sn号。1.我通过Build.SERIAL去取sn号，为unkown。2.在RKGlassDevice#initUsbDevice(...)回调函数中，我们可以获取到眼镜的基本信息GlassInfo，sn 区分眼镜唯一标识序列号。
> 是不是眼镜的ID，不管连盒子还是Android设备都是通过2来获得的。

你好，关于获取sn号，我们的系统是基于android9，Build.SERIAL在android8已经废弃，android8以后的系统，可以使用Build.getSerial()方法获取sn

**Comment by LimboG** [comment]
> 在眼镜RG-202上，运行sdk_facesdk_demo-11ce62b，第一次相机预览黑屏，重启眼镜之后，打开sdk_facesdk_demo-11ce62b，人脸识别界面正常（有预览界面，可以识别人脸）
兄弟，我也遇到了第一次打不开摄像头，要重启才行，你解决了吗

**Comment by LimboG** [comment]
> 在眼镜RG-202上，运行sdk_facesdk_demo-11ce62b，第一次相机预览黑屏，重启眼镜之后，打开sdk_facesdk_demo-11ce62b，人脸识别界面正常（有预览界面，可以识别人脸）
> 
>  29f9631e3a29360a87c81557f25cb4e6.mp4 
> 
> 日志是这样的：
> `2021-07-22 19:47:49.710 8044-8044/com.rokid.rokidfacesample W/ActivityThread: handleWindowVisibility: no activity for token android.os.BinderProxy@cd2565a 2021-07-22 19:47:49.797 8044-8258/com.rokid.rokidfacesample W/CameraBase: An error occurred while connecting to camera 0: Status(-8): '7: connectHelper:1333: Higher-priority client using camera, ID "0" currently unavailable' 2021-07-22 19:47:49.797 8044-8258/com.rokid.rokidfacesample W/System.err: java.lang.RuntimeException: Fail to connect to camera service 2021-07-22 19:47:49.798 8044-8258/com.rokid.rokidfacesample W/System.err: at android.hardware.Camera.<init>(Camera.java:546) 2021-07-22 19:47:49.798 8044-8258/com.rokid.rokidfacesample W/System.err: at android.hardware.Camera.open(Camera.java:392) 2021-07-22 19:47:49.798 8044-8258/com.rokid.rokidfacesample W/System.err: at com.rokid.camerakit.cameralibrary.CameraManage.openCamera(CameraManage.java:52) 2021-07-22 19:47:49.798 8044-8258/com.rokid.rokidfacesample W/System.err: at com.rokid.camerakit.cameralibrary.view.CameraView$3.run(CameraView.java:98) 2021-07-22 19:47:49.799 8044-8258/com.rokid.rokidfacesample W/System.err: at android.os.Handler.handleCallback(Handler.java:873) 2021-07-22 19:47:49.799 8044-8258/com.rokid.rokidfacesample W/System.err: at android.os.Handler.dispatchMessage(Handler.java:99) 2021-07-22 19:47:49.799 8044-8258/com.rokid.rokidfacesample W/System.err: at android.os.Looper.loop(Looper.java:193) 2021-07-22 19:47:49.799 8044-8258/com.rokid.rokidfacesample W/System.err: at android.os.HandlerThread.run(HandlerThread.java:65) 2021-07-22 19:47:49.870 8044-8044/com.rokid.rokidfacesample E/[cit_faceeng_video]: dumpiqa false 2021-07-22 19:47:49.870 8044-8044/com.rokid.rokidfacesample E/[cit_faceeng_video]: dumpfeat false 2021-07-22 19:47:49.872 8044-8044/com.rokid.rokidfacesample E/[TownLine] [searchengine] [JNI]: dumprecog true 2021-07-22 19:47:49.893 8044-8258/com.rokid.rokidfacesample W/CameraBase: An error occurred while connecting to camera 0: Status(-8):`

兄弟，我也遇到了这种情况，第一次打不开相机，重启才正常，你解决了吗

**Comment by lanyuqingri** [comment]
@LimboG 你好，你那边打不开相机时的日志是怎样的？ 也是如上边类似的报错吗？

**Comment by LimboG** [comment]
> @LimboG 你好，你那边打不开相机时的日志是怎样的？ 也是如上边类似的报错吗？

应该是同一个问题

**Comment by lanyuqingri** [comment]
@LimboG 可以确认下是否是同一个问题，如果是的话，可以在开发是使用camera2 的api 来进行camera相关的操作，在我们的二代眼镜系统上，这样就不会有camera打不开的问题。

**Comment by LimboG** [comment]
> @LimboG 可以确认下是否是同一个问题，如果是的话，可以在开发是使用camera2 的api 来进行camera相关的操作，在我们的二代眼镜系统上，这样就不会有camera打不开的问题。

用的sdk不支持camera2 api

**Comment by lanyuqingri** [comment]
@LimboG sample里边用的不是camera2的api，对实际的人脸识别sdk来说，只是关心数据，咱们再开发自己的应用时可以使用camera2的api来做数据获取，我们内部后续也优化下这份sample，对使用sample上造成的困扰深感抱歉，咱们这边可以先参考下人脸识别相关的接口调用，然后再根据自己实际的场景需要来开发，还请知悉。
