### ISSUE TITLE
armeabi-v7a架构下启动离线人脸识别Demo崩溃

### ISSUE THREAD

**Issue by LeooooL** [RokidGlass/glass2-docs#64]
java.lang.UnsatisfiedLinkError: dlopen failed: library "libovxlib.so" not found
        at java.lang.Runtime.loadLibrary0(Runtime.java:1016)
        at java.lang.System.loadLibrary(System.java:1657)
        at com.rokid.citrus.citrusfacesdk.CitrusFaceEngine.<clinit>(CitrusFaceEngine.java:32)
        at com.rokid.citrus.citrusfacesdk.CitrusFaceEngine.Init(CitrusFaceEngine.java:152)

**Comment by zvlwwj** [comment]
@LeooooL 请问是在眼镜上跑这个SDK Demo吗？

**Comment by LeooooL** [comment]
不是呢 我用手机跑的 arm64-v8a架构下是可以运行的  手机：一加6T  Android 10.0

**Comment by zvlwwj** [comment]
@LeooooL 由于考虑到npu的兼容性问题，手机的armeabi-v7a在这个版本是不支持的，下个版本会将CPU版本和NPU版本分开发布，手机端只需要集成CPU版本，就能解决这个问题。

**Comment by LeooooL** [comment]
好的 可以问一下预计什么时候会出新版本吗

**Comment by zvlwwj** [comment]
@LeooooL 国庆节后第一周就能发布
